language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install: 
  - pip install django==$DJANGO_VERSION --quiet
  - pip install Pillow>=2.0.0 coverage==3.5 html5lib==1.0b8 httplib2==0.7.6 nose==1.3.3 pyPdf2==1.19 reportlab>=3.0 six Sphinx==1.4.8 sphinx-rtd-theme==0.1.9
  - pip install xhtml2pdf --quiet

# command to run tests
script: python manage.py test

env:
  - DJANGO_VERSION=1.8.16
  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.10.3

