language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install: 
  - pip install xhtml2pdf==0.1b1 --quiet
  - pip install django==$DJANGO_VERSION --quiet

# command to run tests
script: python manage.py test

env:
  - DJANGO_VERSION=1.8.16
  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.10.3

